CREATE DATABASE IF NOT EXISTS menu_randomizer CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE menu_randomizer;

CREATE TABLE IF NOT EXISTS `menu` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `category` varchar(50) NOT NULL COMMENT 'adult or baby',
  `description` text,
  `image` varchar(255),
  `ingredients` text,
  `steps` text,
  `nutrition` text,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 初始化成人菜单数据
INSERT INTO `menu` (`name`, `category`, `description`, `image`, `ingredients`, `steps`, `nutrition`) VALUES
('宫保鸡丁', 'adult', '经典川菜，香辣可口', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Chinese%20Kung%20Pao%20Chicken%20dish%20with%20peanuts%20and%20vegetables&image_size=square', '鸡肉200g,花生50g,青椒50g,干辣椒10g,蒜5g,姜5g,料酒10ml,生抽15ml,老抽5ml,糖5g,盐2g', '1. 鸡肉切丁，用料酒、生抽腌制10分钟\n2. 花生炸熟备用\n3. 锅中放油，爆香姜蒜和干辣椒\n4. 放入鸡丁翻炒至变色\n5. 加入青椒翻炒\n6. 加入调味汁和花生翻炒均匀', '{"calories": 350, "protein": 25, "fat": 20, "carbs": 15}'),
('麻婆豆腐', 'adult', '四川传统名菜，麻辣鲜香', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Mapo%20Tofu%20Sichuan%20dish%20with%20tofu%20and%20spicy%20sauce&image_size=square', '豆腐500g,牛肉末100g,豆瓣酱20g,花椒粉5g,蒜5g,姜5g,葱花10g,生抽10ml,糖5g,盐2g', '1. 豆腐切块，焯水备用\n2. 锅中放油，爆香姜蒜\n3. 加入牛肉末翻炒至变色\n4. 加入豆瓣酱炒出红油\n5. 加入豆腐块，轻轻翻炒\n6. 加入调味汁，煮2分钟\n7. 撒上花椒粉和葱花', '{"calories": 300, "protein": 20, "fat": 15, "carbs": 10}'),
('糖醋排骨', 'adult', '酸甜可口，老少皆宜', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sweet%20and%20sour%20ribs%20Chinese%20dish&image_size=square', '排骨500g,生姜10g,大蒜5g,料酒15ml,生抽15ml,老抽5ml,醋20ml,糖30g,盐2g', '1. 排骨焯水，去除血水\n2. 锅中放油，爆香姜蒜\n3. 放入排骨翻炒至金黄色\n4. 加入料酒、生抽、老抽\n5. 加入适量清水，大火烧开后转小火炖30分钟\n6. 加入糖和醋，大火收汁\n7. 撒上芝麻点缀', '{"calories": 400, "protein": 25, "fat": 25, "carbs": 20}'),
('鱼香肉丝', 'adult', '川菜经典，鱼香浓郁', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Yuxiang%20Shredded%20Pork%20Chinese%20dish&image_size=square', '猪里脊200g,青椒50g,胡萝卜50g,木耳30g,蒜5g,姜5g,泡椒10g,料酒10ml,生抽15ml,老抽5ml,糖10g,醋10ml', '1. 猪肉切丝，用料酒、生抽腌制10分钟\n2. 青椒、胡萝卜、木耳切丝\n3. 锅中放油，爆香姜蒜和泡椒\n4. 放入肉丝翻炒至变色\n5. 加入蔬菜丝翻炒\n6. 加入调味汁翻炒均匀', '{"calories": 320, "protein": 22, "fat": 18, "carbs": 15}'),
('红烧肉', 'adult', '传统名菜，肥而不腻', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Braised%20pork%20belly%20Chinese%20dish&image_size=square', '五花肉500g,生姜10g,大蒜5g,八角2个,桂皮1小块,料酒15ml,生抽15ml,老抽10ml,糖20g,盐2g', '1. 五花肉切块，焯水备用\n2. 锅中放油，放入五花肉煎至金黄色\n3. 加入姜蒜、八角、桂皮爆香\n4. 加入料酒、生抽、老抽\n5. 加入适量清水，大火烧开后转小火炖1小时\n6. 加入糖，大火收汁\n7. 撒上葱花', '{"calories": 450, "protein": 20, "fat": 35, "carbs": 15}'),
('清蒸鱼', 'adult', '清淡鲜美，营养丰富', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Steamed%20fish%20Chinese%20dish&image_size=square', '鱼1条(约500g),生姜10g,葱10g,料酒10ml,生抽15ml,盐2g', '1. 鱼处理干净，在鱼身上划几刀\n2. 鱼身上撒盐，淋料酒\n3. 鱼腹内放入姜葱\n4. 蒸锅水开后放入鱼，蒸10分钟\n5. 取出鱼，倒掉蒸出的水\n6. 在鱼身上淋生抽\n7. 锅中放油烧热，浇在鱼身上\n8. 撒上葱花', '{"calories": 250, "protein": 25, "fat": 10, "carbs": 5}'),
('西红柿炒鸡蛋', 'adult', '家常经典，酸甜可口', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tomato%20and%20egg%20stir%20fry%20Chinese%20dish&image_size=square', '西红柿2个,鸡蛋3个,葱花5g,盐3g,糖5g', '1. 鸡蛋打散，炒熟备用\n2. 西红柿切块\n3. 锅中放油，放入西红柿翻炒出汁\n4. 加入糖和盐调味\n5. 加入炒好的鸡蛋翻炒均匀\n6. 撒上葱花', '{"calories": 200, "protein": 15, "fat": 10, "carbs": 15}'),
('青椒土豆丝', 'adult', '清爽开胃，简单易做', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Green%20pepper%20and%20potato%20stir%20fry%20Chinese%20dish&image_size=square', '土豆2个,青椒1个,蒜5g,盐3g,醋5ml', '1. 土豆切丝，泡水去除淀粉\n2. 青椒切丝\n3. 锅中放油，爆香蒜\n4. 放入土豆丝翻炒\n5. 加入青椒丝翻炒\n6. 加入盐和醋调味\n7. 翻炒均匀即可', '{"calories": 180, "protein": 3, "fat": 8, "carbs": 25}'),
('可乐鸡翅', 'adult', '甜香可口，深受喜爱', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Cola%20chicken%20wings%20Chinese%20dish&image_size=square', '鸡翅8个,可乐1罐,生姜10g,大蒜5g,料酒10ml,生抽15ml,老抽5ml,盐2g', '1. 鸡翅焯水，去除血水\n2. 锅中放油，爆香姜蒜\n3. 放入鸡翅翻炒至金黄色\n4. 加入料酒、生抽、老抽\n5. 倒入可乐，没过鸡翅\n6. 大火烧开后转小火炖20分钟\n7. 大火收汁\n8. 撒上芝麻', '{"calories": 380, "protein": 20, "fat": 25, "carbs": 15}'),
('酸辣土豆丝', 'adult', '酸辣开胃，下饭菜', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Spicy%20and%20sour%20potato%20stir%20fry%20Chinese%20dish&image_size=square', '土豆2个,干辣椒5个,蒜5g,醋10ml,盐3g,糖3g', '1. 土豆切丝，泡水去除淀粉\n2. 锅中放油，爆香干辣椒和蒜\n3. 放入土豆丝翻炒\n4. 加入醋、盐、糖调味\n5. 翻炒均匀即可', '{"calories": 190, "protein": 3, "fat": 9, "carbs": 25}'),
('蒜蓉西兰花', 'adult', '清淡健康，营养丰富', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Garlic%20broccoli%20Chinese%20dish&image_size=square', '西兰花250g,大蒜10g,蚝油10ml,盐2g', '1. 西兰花切小朵，焯水备用\n2. 锅中放油，爆香蒜末\n3. 放入西兰花翻炒\n4. 加入蚝油和盐调味\n5. 翻炒均匀即可', '{"calories": 120, "protein": 5, "fat": 7, "carbs": 10}'),
('白灼虾', 'adult', '鲜美多汁，保留原味', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Boiled%20shrimp%20Chinese%20dish&image_size=square', '虾500g,生姜10g,葱10g,料酒10ml,盐2g', '1. 虾处理干净\n2. 锅中烧水，加入姜葱和料酒\n3. 水开后放入虾，煮2-3分钟\n4. 捞出虾，沥干水分\n5. 蘸料：生抽+芥末或醋+蒜末', '{"calories": 200, "protein": 25, "fat": 5, "carbs": 5}'),
('红烧茄子', 'adult', '软糯香甜，下饭神器', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Braised%20eggplant%20Chinese%20dish&image_size=square', '茄子2个,猪肉末50g,蒜5g,姜5g,生抽15ml,老抽5ml,糖10g,盐2g', '1. 茄子切块，油炸至金黄色\n2. 锅中放油，爆香姜蒜\n3. 放入猪肉末翻炒至变色\n4. 加入茄子翻炒\n5. 加入生抽、老抽、糖、盐调味\n6. 加入适量清水，炖5分钟\n7. 大火收汁', '{"calories": 300, "protein": 8, "fat": 20, "carbs": 25}'),
('宫保虾球', 'adult', '香辣可口，营养丰富', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Kung%20Pao%20shrimp%20balls%20Chinese%20dish&image_size=square', '虾仁200g,花生50g,青椒50g,干辣椒10g,蒜5g,姜5g,料酒10ml,生抽15ml,老抽5ml,糖5g,盐2g', '1. 虾仁用料酒、生抽腌制10分钟\n2. 花生炸熟备用\n3. 锅中放油，爆香姜蒜和干辣椒\n4. 放入虾仁翻炒至变色\n5. 加入青椒翻炒\n6. 加入调味汁和花生翻炒均匀', '{"calories": 320, "protein": 25, "fat": 18, "carbs": 15}'),
('糖醋里脊', 'adult', '酸甜可口，外酥里嫩', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sweet%20and%20sour%20pork%20tenderloin%20Chinese%20dish&image_size=square', '猪里脊200g,鸡蛋1个,淀粉50g,料酒10ml,生抽10ml,醋20ml,糖30g,盐2g', '1. 猪里脊切块，用料酒、生抽腌制10分钟\n2. 鸡蛋打散，加入淀粉调成面糊\n3. 里脊肉裹上面糊，油炸至金黄色\n4. 锅中放油，加入糖、醋、盐调成糖醋汁\n5. 放入炸好的里脊肉翻炒均匀\n6. 撒上芝麻', '{"calories": 400, "protein": 20, "fat": 20, "carbs": 30}'),
('水煮肉片', 'adult', '麻辣鲜香，刺激味蕾', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Boiled%20pork%20slices%20Sichuan%20dish&image_size=square', '猪里脊200g,豆芽100g,青菜100g,干辣椒10g,花椒5g,蒜5g,姜5g,豆瓣酱20g,生抽15ml,盐2g', '1. 猪里脊切片，用淀粉、生抽腌制10分钟\n2. 豆芽和青菜焯水备用\n3. 锅中放油，爆香姜蒜、干辣椒、花椒\n4. 加入豆瓣酱炒出红油\n5. 加入清水，烧开后放入肉片\n6. 肉片熟后，连汤倒入装有蔬菜的碗中\n7. 撒上花椒和干辣椒，浇热油', '{"calories": 350, "protein": 25, "fat": 20, "carbs": 15}'),
('油焖大虾', 'adult', '鲜香味美，色泽红亮', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Braised%20prawns%20Chinese%20dish&image_size=square', '大虾500g,生姜10g,大蒜5g,料酒10ml,生抽15ml,老抽5ml,糖10g,盐2g', '1. 大虾处理干净，剪去须脚\n2. 锅中放油，爆香姜蒜\n3. 放入大虾翻炒至变色\n4. 加入料酒、生抽、老抽\n5. 加入适量清水，焖5分钟\n6. 加入糖和盐调味\n7. 大火收汁\n8. 撒上葱花', '{"calories": 300, "protein": 25, "fat": 15, "carbs": 10}'),
('酱爆鸡丁', 'adult', '酱香浓郁，口感丰富', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sauce%20stir%20fried%20chicken%20dice%20Chinese%20dish&image_size=square', '鸡肉200g,青椒50g,胡萝卜50g,蒜5g,姜5g,甜面酱20g,料酒10ml,生抽10ml,糖5g', '1. 鸡肉切丁，用料酒、生抽腌制10分钟\n2. 青椒、胡萝卜切丁\n3. 锅中放油，爆香姜蒜\n4. 放入鸡丁翻炒至变色\n5. 加入甜面酱翻炒\n6. 加入青椒和胡萝卜翻炒\n7. 加入糖调味\n8. 翻炒均匀即可', '{"calories": 320, "protein": 22, "fat": 18, "carbs": 15}'),
('蒜蓉粉丝蒸扇贝', 'adult', '鲜美多汁，营养丰富', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Steamed%20scallops%20with%20garlic%20and%20vermicelli%20Chinese%20dish&image_size=square', '扇贝10个,粉丝50g,大蒜20g,生抽15ml,蚝油10ml,盐2g', '1. 扇贝处理干净，粉丝泡软\n2. 大蒜切末，加入生抽、蚝油、盐调成蒜蓉酱\n3. 粉丝铺在扇贝上，淋上蒜蓉酱\n4. 蒸锅水开后放入扇贝，蒸5分钟\n5. 取出撒上葱花，浇热油', '{"calories": 250, "protein": 20, "fat": 10, "carbs": 20}'),
('红烧鱼', 'adult', '鲜香可口，肉质鲜嫩', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Braised%20fish%20Chinese%20dish&image_size=square', '鱼1条(约500g),生姜10g,大蒜5g,八角2个,桂皮1小块,料酒15ml,生抽15ml,老抽10ml,糖10g,盐2g', '1. 鱼处理干净，在鱼身上划几刀\n2. 锅中放油，将鱼煎至金黄色\n3. 加入姜蒜、八角、桂皮爆香\n4. 加入料酒、生抽、老抽\n5. 加入适量清水，大火烧开后转小火炖20分钟\n6. 加入糖和盐调味\n7. 大火收汁\n8. 撒上葱花', '{"calories": 300, "protein": 25, "fat": 15, "carbs": 10}');

-- 初始化婴儿菜单数据
INSERT INTO `menu` (`name`, `category`, `description`, `image`, `ingredients`, `steps`, `nutrition`) VALUES
('胡萝卜泥', 'baby', '适合6个月以上婴儿，富含维生素A', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Carrot%20puree%20for%20baby%20food&image_size=square', '胡萝卜2根', '1. 胡萝卜洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 40, "protein": 1, "fat": 0, "carbs": 10, "vitaminA": "丰富"}'),
('南瓜泥', 'baby', '适合6个月以上婴儿，口感香甜', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Pumpkin%20puree%20for%20baby%20food&image_size=square', '南瓜200g', '1. 南瓜洗净，去皮切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 30, "protein": 1, "fat": 0, "carbs": 8, "fiber": "丰富"}'),
('土豆泥', 'baby', '适合6个月以上婴儿，口感细腻', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Potato%20puree%20for%20baby%20food&image_size=square', '土豆2个', '1. 土豆洗净，去皮切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量母乳或配方奶调稀', '{"calories": 50, "protein": 1, "fat": 0, "carbs": 12}'),
('苹果泥', 'baby', '适合6个月以上婴儿，富含维生素C', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Apple%20puree%20for%20baby%20food&image_size=square', '苹果1个', '1. 苹果洗净，去皮去核\n2. 切块放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可直接食用', '{"calories": 45, "protein": 0, "fat": 0, "carbs": 12, "vitaminC": "丰富"}'),
('香蕉泥', 'baby', '适合6个月以上婴儿，天然甜味', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Banana%20puree%20for%20baby%20food&image_size=square', '香蕉1根', '1. 香蕉去皮\n2. 用勺子压成泥\n3. 可直接食用或加入米粉中', '{"calories": 80, "protein": 1, "fat": 1, "carbs": 20, "potassium": "丰富"}'),
('牛油果泥', 'baby', '适合6个月以上婴儿，富含健康脂肪', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Avocado%20puree%20for%20baby%20food&image_size=square', '牛油果1个', '1. 牛油果去皮去核\n2. 用勺子压成泥\n3. 可直接食用或加入米粉中', '{"calories": 120, "protein": 2, "fat": 10, "carbs": 6, "vitaminK": "丰富"}'),
('鸡肉泥', 'baby', '适合7个月以上婴儿，富含蛋白质', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Chicken%20puree%20for%20baby%20food&image_size=square', '鸡胸肉50g', '1. 鸡胸肉洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 60, "protein": 12, "fat": 1, "carbs": 0}'),
('鱼肉泥', 'baby', '适合7个月以上婴儿，富含DHA', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Fish%20puree%20for%20baby%20food&image_size=square', '鳕鱼50g', '1. 鳕鱼洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥，注意挑出鱼刺\n4. 可加入适量温水调稀', '{"calories": 50, "protein": 10, "fat": 2, "carbs": 0, "DHA": "丰富"}'),
('蔬菜泥', 'baby', '适合7个月以上婴儿，多种维生素', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Vegetable%20puree%20for%20baby%20food&image_size=square', '菠菜50g,胡萝卜50g,土豆50g', '1. 所有蔬菜洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 40, "protein": 2, "fat": 0, "carbs": 8, "vitamins": "丰富"}'),
('米粉', 'baby', '适合6个月以上婴儿，第一口辅食', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Rice%20cereal%20for%20baby%20food&image_size=square', '婴儿米粉20g,温水或母乳/配方奶', '1. 将米粉倒入碗中\n2. 加入适量温水或母乳/配方奶\n3. 搅拌成糊状\n4. 温度适宜后喂食', '{"calories": 80, "protein": 2, "fat": 1, "carbs": 16}'),
('红薯泥', 'baby', '适合6个月以上婴儿，富含膳食纤维', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Sweet%20potato%20puree%20for%20baby%20food&image_size=square', '红薯200g', '1. 红薯洗净，去皮切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 80, "protein": 1, "fat": 0, "carbs": 20, "fiber": "丰富"}'),
('豌豆泥', 'baby', '适合7个月以上婴儿，富含蛋白质', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Pea%20puree%20for%20baby%20food&image_size=square', '豌豆100g', '1. 豌豆洗净\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 60, "protein": 4, "fat": 1, "carbs": 10, "fiber": "丰富"}'),
('梨泥', 'baby', '适合6个月以上婴儿，清热润肺', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Pear%20puree%20for%20baby%20food&image_size=square', '梨1个', '1. 梨洗净，去皮去核\n2. 切块放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可直接食用', '{"calories": 50, "protein": 0, "fat": 0, "carbs": 13, "vitaminC": "丰富"}'),
('西兰花泥', 'baby', '适合7个月以上婴儿，富含维生素C', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Broccoli%20puree%20for%20baby%20food&image_size=square', '西兰花100g', '1. 西兰花洗净，切小朵\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 30, "protein": 3, "fat": 0, "carbs": 5, "vitaminC": "丰富"}'),
('豆腐泥', 'baby', '适合8个月以上婴儿，富含钙', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tofu%20puree%20for%20baby%20food&image_size=square', '嫩豆腐100g', '1. 豆腐洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 40, "protein": 4, "fat": 2, "carbs": 2, "calcium": "丰富"}'),
('蛋黄泥', 'baby', '适合8个月以上婴儿，富含铁', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Egg%20yolk%20puree%20for%20baby%20food&image_size=square', '鸡蛋1个', '1. 鸡蛋煮熟\n2. 取蛋黄部分\n3. 用勺子压成泥\n4. 可加入适量温水或母乳/配方奶调稀', '{"calories": 60, "protein": 3, "fat": 5, "carbs": 1, "iron": "丰富"}'),
('燕麦泥', 'baby', '适合8个月以上婴儿，富含膳食纤维', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Oatmeal%20puree%20for%20baby%20food&image_size=square', '燕麦片20g,温水或母乳/配方奶', '1. 燕麦片洗净\n2. 放入锅中煮熟\n3. 用辅食机打成泥\n4. 可加入适量温水或母乳/配方奶调稀', '{"calories": 80, "protein": 3, "fat": 2, "carbs": 15, "fiber": "丰富"}'),
('番茄泥', 'baby', '适合8个月以上婴儿，富含维生素C', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Tomato%20puree%20for%20baby%20food&image_size=square', '番茄1个', '1. 番茄洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 20, "protein": 1, "fat": 0, "carbs": 5, "vitaminC": "丰富"}'),
('鸡肉蔬菜泥', 'baby', '适合9个月以上婴儿，营养均衡', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Chicken%20and%20vegetable%20puree%20for%20baby%20food&image_size=square', '鸡胸肉50g,胡萝卜50g,土豆50g', '1. 所有食材洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥\n4. 可加入适量温水调稀', '{"calories": 70, "protein": 12, "fat": 1, "carbs": 10, "vitamins": "丰富"}'),
('鱼肉蔬菜泥', 'baby', '适合9个月以上婴儿，富含DHA', 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=Fish%20and%20vegetable%20puree%20for%20baby%20food&image_size=square', '鳕鱼50g,西兰花50g,土豆50g', '1. 所有食材洗净，切块\n2. 放入蒸锅蒸熟\n3. 用辅食机打成泥，注意挑出鱼刺\n4. 可加入适量温水调稀', '{"calories": 60, "protein": 10, "fat": 2, "carbs": 8, "DHA": "丰富"}');